ALTER TYPE dataspace_exchange_message_type ADD VALUE IF NOT EXISTS 'TAKT_RESPONSE_ACCEPTED';
ALTER TYPE dataspace_exchange_message_type ADD VALUE IF NOT EXISTS 'TAKT_RESPONSE_REVISION_REQUESTED';
ALTER TYPE dataspace_exchange_message_type ADD VALUE IF NOT EXISTS 'TAKT_REQUEST_CANCELLED';